# Generated by Django 2.1.13 on 2021-10-05 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=250)),
                ('patient', models.CharField(max_length=250)),
                ('hospital_date', models.DateField()),
                ('alta_date', models.DateField()),
                ('prevision_date', models.DateField()),
                ('action', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=250)),
                ('pam', models.CharField(max_length=250)),
                ('prevision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testings.Prevision')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testings.Status')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
